### PR TITLE
[ENH] Add new datasets: India census

### LINKED ISSUE #29: Geo add-on: no datasets
##### Geo version
current and probably all versions

##### Orange version
...

##### Expected behavior
Maybe add-on should have some datasets with geo information included.

However I know that at least one dataset with geo data can be obtained via **Data Sets** widget in Core (_Illegal waste dumpsites in Slovenia (2017)_).

##### Actual behavior
No datasets.

##### Steps to reproduce the behavior
Check Geo add-on's folders.

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
Fixes #29 .

##### Includes
- [ ] Code changes
- [ ] Tests
- [ ] Documentation
- [x] Datasets

### CODE REVIEW

**Comment by kernc** [comment]
Can use the dataset in widget's __main__ blocks?

**Comment by jerneju** [comment]
@kernc : Sure, just some code is needed before opening:

```python
from os.path import dirname
from Orange.data.table import dataset_dirs
from pathlib import Path
dataset_dirs.insert(0, str(Path(dirname(__file__)).parent.joinpath("datasets")))
del dirname, dataset_dirs, Path
```

and then it works:
```python
data = Table("India_census_district_population")
```

**Comment by kernc** [comment]
👍

Can _you_ make use of the dataset in widget's `__main__` blocks _before we merge this_?

Can put that `dataset_dirs` snippet in _orangecontrib/geo/\_\_init\_\_.py_ (possibly with `path.dirname` and `path.join` instead of the abhorrent pathlib).

**Comment by jerneju** [comment]
Fixed.

**Pull request merged**
