### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by larazupan**

### CODE REVIEW

**Comment by kernc** [comment]
The icons are distinguishable in the toolbox, but no so much once bezelled on the canvas. Can the important features be made bolder?
screenshot_2017-12-01_17-31-18

Also notice the updated [map icon](https://github.com/biolab/orange3-geo/blob/master/orangecontrib/geo/widgets/icons/GeoMap.svg). Falls out of place with the current theme, but looks more intuitive than the former. Can you do something in that manner?

**Comment by markotoplak** [comment]
As @kerns said, these icons do not work well with the background.

Also, to me it seems that the globes are:
(1) too small (they do not use the available space and will be thus harder to recognize).
(2) some are non-centered.

**Comment by BlazZupan** [comment]
I propose to start by keeping the icons, but try to change the background.

It would be hard to design the icons with the globes in the center (I actually find it nice that the globe moves from the center, depending on an icon).

**Comment by kernc** [comment]
The changed color is acceptable.

Could you perhaps also update Choropleth icon to match the other two _in size_?

**Pull request merged**
