### PR TITLE
OWMap: disable redrawing when setting map data

### LINKED ISSUE #51: GeoMap: crash on mismatching settings
##### Issue
Geo Map crashes Orange.
```
Error calling 'set_data' of 'Geo Map'
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/canvas/scheme/widgetsscheme.py", line 1072, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 833, in set_data
    self.map.set_data(self.data, self.lat_attr, self.lon_attr)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 141, in set_data
    self.redraw_markers_overlay_image(new_image=True)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 475, in redraw_markers_overlay_image
    self._update_js_markers(visible, in_subset[visible])
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 391, in _update_js_markers
    for rgb in self._colorgen.getRGB(self._scaled_color_values[visible])]
IndexError: index 5 is out of bounds for axis 0 with size 1
---------------------------- IndexError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 51, in redraw_markers_overlay_image
    return self.redraw_markers_overlay_image(*args)
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 475, in redraw_markers_overlay_image
    self._update_js_markers(visible, in_subset[visible])
  File "/Users/ajda/orange/orange3-geo/orangecontrib/geo/widgets/owmap.py", line 391, in _update_js_markers
    for rgb in self._colorgen.getRGB(self._scaled_color_values[visible])]
IndexError: index 14 is out of bounds for axis 0 with size 1
-------------------------------------------------------------------------------
```

##### Steps to reproduce
File (any with lat/lon) - Geo Map. Set a couple of things, color, size, shape. I was using HDI, with shape set to Child labour, where there are many values. Legend was set.
Then I inserted Data Table between File and Geo Map and selected a couple of instances from the table. Geo Map reports the first error.
Then I open GeoMap and try to re-plot the points by pressing Center map. This crashes Orange.

### PR DESCRIPTION
**Pull request by robertcv**
##### Issue
Fixes #51 
Data points where redrawen on new data befor color/label/shape/size where updated.
##### Description of changes
Disable redrawing on setting map data. 
##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@kernc Would you mind adding me and @robertcv as admins for the repo so we can work on the release of the add-on this week? Thanks!

**Comment by robertcv** [comment]
The falling test is fixed in #65.

**Comment by kernc** [comment]
> @kernc Would you mind adding me and @robertcv as admins for the repo so we can work on the release of the add-on this week? Thanks!

Sure wouldn't. But I'm no longer a privileged user here. :sweat_smile: cc: @janezd

**Comment by ajdapretnar** [comment]
@kernc Ok, I didn't know. Just assumed from Collaborators list. 🤷‍♀ Will ask Janez.
#65 is now merged. Probably rebase for tests to pass here @robertcv.

**Comment by kernc** [comment]
> Ok, I didn't know. Just assumed from Collaborators list. :woman_shrugging: 

Yeah, I think there might have been reports of unmannered radicals being hosted by your organization some two months ago, resulting in expedient and exhaustive purge of inactive members. :sweat_smile:

**Pull request merged**
