### PR TITLE
GeoMapper: override matching

### PR DESCRIPTION
**Pull request by kernc**
##### Issue
Fixes https://github.com/biolab/orange3-geo/issues/16, fixes https://github.com/biolab/orange3-geo/issues/13.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kernc** [comment]
Try nao.

**Comment by astaric** [comment]
I can edit replacements, but they do not work. Aliases do not work either:

screen shot 2017-10-06 at 21 20 48

In the screenshot, I had Kočevje marked as no match, so I mapped it to Kočevje (the same string), and applied. The region still did not show on map.

**Comment by kernc** [comment]
So the problem is you are permitted to input an invalid string (Kočevje vs.
Kocevje found in the completer list)?

**Comment by astaric** [comment]
I did not input it, I have selected in from the "dropdown"

**Comment by astaric** [comment]
I think I know where the problem is, I need to update the json files

**Comment by astaric** [comment]
This solved the problem.

There is only one "weird" region left in the "database", `Šmartno in Litiji`, which should be `Šmartno pri Litiji`. Do we fix that one with mapping as well?

**Comment by astaric** [comment]
(the current mapping has S instead of Š in the replacement)

**Comment by kernc** [comment]
Fixed S→Š.

**Comment by astaric** [comment]
can you try modifying the main() in owgeocoding to
```
    from AnyQt.QtWidgets import QApplication
    a = QApplication([])
    data = Table('/Users/anze/Desktop/OsebnaVozila.tab')

    ow = OWGeocoding()
    ow.show()
    ow.raise_()

    print(data[:10])
    import time
    time.sleep(10)

    ow.set_data(data)
    ow.is_decoding = 0
    ow.str_attr = "C1.3-Obcina uporabnika vozila (opis)"
    ow.str_type = "Region name"
    start = time.time()
    ow.unconditional_commit()
    print(time.time()-start)

    a.exec()
```

and compare the times on master and this PR? I get about 10x slowdown (0.3s against 3s) on a 80k rows dataset. Anything you can do about it?

**Comment by kernc** [comment]
How is 1.7x slower; resolving country names 10x faster?

**Comment by astaric** [comment]
I get the following error:
```
...
File "/Users/anze/dev/orange3-geo/orangecontrib/geo/mapper.py", line 174, in _get
    mapping.set_axis(mapping.values.copy(), axis=0, inplace=True)
TypeError: set_axis() got multiple values for argument 'axis'
```
mapping is a Series object, I am using pandas==0.20.3

**Comment by kernc** [comment]
Sorry, `inplace=True` was added in 0.21.0. Needlessly complicated anyway. Find replaced.

**Comment by astaric** [comment]
Works like a charm.

I have found one more replacement:
  - Solčava -> Solcava (it was at the top edge of the map so I did not notice it before)

Let me know when you add it and I will merge.

**Comment by kernc** [comment]
Pushed.

**Comment by astaric** [comment]
Thanks

**Pull request merged**
